# Name of workflow as seen in Github actions tab
name: dev-build-and-deploy
# Run workflow only on push to master branch
on:
  push:
    branches:
      - master
jobs:
  # To build the project
  build-ilum:
    name: Deploy_Dev
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: Checking out code
        uses: actions/checkout@v3

      - name: Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Installing dependencies
        run: yarn install

      - name: Building project
        run: npm run build:qa

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Deploy to S3 bucket
        run: aws s3 sync build s3://${{ vars.BUCKET }} --exclude '*.map' --delete
